format_version = 1
welcome_message = """
Welcome to the Viasat Rust Interview exercises.

This set is based on Rustlings, but is a minimal collection of questions designed to test your practical Rust knowledge.

Each exercise may contain compiler or logic errors. Your task is to fix the code so that it compiles and passes any tests.

Open the indicated file, make your changes, and save. Progress will be tracked automatically.

If you get stuck, hints are available for some exercises.

Good luck!
"""

final_message = """
Congratulations on completing the Viasat Rust Interview exercises!"""

# INTRO

[[exercises]]
name = "intro1"
dir = "00_intro"
test = false
skip_check_unsolved = true
hint = """
From: Rustlings
Enter `n` to move on to the next exercise.
You might need to press ENTER after typing `n`."""

[[exercises]]
name = "intro2"
dir = "00_intro"
test = false
hint = """ 
From: Rustlings
The compiler is informing us that we've got the name of the print macro wrong.
It also suggests an alternative."""

# BASIC
[[exercises]]
name = "basic1"
dir = "01_basic"
test = false
hint = """
This is a simple lifetime exercise, similiar to the famouse \"longest\" example, but with a twist
- We have 3 string slices, and we want to return the one with the most characters."""

[[exercises]]
name = "basic2"
dir = "01_basic"
hint = """
This is a simple ownership and types exercise. 
- The tests expect an enum that can represent either a String or an integer.
- Fix the failures by defining the enum then changing usage to either take ownership or reference as needed."""

[[exercises]]
name = "basic3"
dir = "01_basic"
hint = """
This is a simple error handling exercise.
- Define a custom error type that can represent the two error conditions.
- Use the custom error type in the function signature."""

# INTERMEDIATE
[[exercises]]
name = "intermediate1"
dir = "02_intermediate"
hint = """
This tests using iterators to process a collection.
- Use iterator methods to transform the input vector into the expected output vector."""

[[exercises]]
name = "intermediate2"
dir = "02_intermediate"
hint = """
This tests using traits and generics and the builder pattern.
- Define a builder trait that can be used for a generic implementation of the builder pattern.
- Implement the trait for the given struct."""

# ADVANCED
[[exercises]]
name = "advanced1"
dir = "03_advanced"
hint = """
This is a more complex problem from the adventofcode.com 2025 challenges.
Parse each line as (dir, n) where dir is 'L' or 'R' and n is the distance;
keep a mutable pos: i32 = 50. For each rotation, compute delta = if dir == 'L' { -n } else { n }, update pos = (pos + delta).rem_euclid(100) to handle wraparound on the 0â€“99 dial, and increment a counter whenever pos == 0. """

# QUIZ 1
[[exercises]]
name = "quiz1"
dir = "quizzes"
hint = "No hints this time ;)"

